version: "3"
services:

  nginx:
    build:
      context: .
      dockerfile: "./.docker/nginx/Dockerfile"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
      - ./.docker/nginx/logs:/var/log/nginx
    links:
      - php
    networks:
      - bridge

  php:
    build:
      context: .
      dockerfile: "./.docker/php/Dockerfile"
    volumes:
      - ./:/var/www
    networks:
      - bridge

  mysql:
    image: mysql:8.0.32
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - bridge

networks:
  bridge:
    driver: bridge